#!/bin/bash
#SBATCH --job-name=si
#SBATCH --account=meng23000
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#
# submit job using:
#
# sbatch runqe
#

module unload espresso
module load espresso/5.1

pw.x < pw_scf.in >& pw_scf.out
pw.x < pw_bands.in >& pw_bands.out
bands.x < bands.in >& bands.out
plotband.x < plotband.in >& plotband.out
